@startuml hal_level

package UL {
    class ul_heart_beat
}

class ul_heart_beat {
    void ulHeartBeatInit(ulHeartBeatStruct* const heartBeat);

    void ulHeartBeatRun(ulHeartBeatStruct* const heartBeat);
}



@enduml